### ISSUE TITLE
Type Information Missing or Malformed in HttpSecurityLambdaDsl Tests

### ISSUE THREAD

**Issue by ohyesgocool** [openrewrite/rewrite-spring#530]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v2.11.0
- Maven/Gradle plugin v5.30.0

## How are you running OpenRewrite?
I have added a Java sample test case in the latest openrewrite project.
You can find the java version [here](https://github.com/freenowtech/rewrite-spring/blob/f064a7c7e7bd2aa99976aa81460e94d3f12eb1d3/src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDslTest.java#L342) 

And the kotlin version [here](https://github.com/freenowtech/rewrite-spring/blob/f064a7c7e7bd2aa99976aa81460e94d3f12eb1d3/src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDslKotlinTest.java#L10)

## What is the smallest, simplest way to reproduce the problem?

you can clone the [repo](https://github.com/freenowtech/rewrite-spring) and and run the tests.

## What is the full stack trace of any errors you encountered?

```
java.lang.IllegalStateException: LST contains missing or invalid type information
Identifier->ClassDeclaration->CompilationUnit
/*~~(Identifier type is missing or malformed)~~>*/WebSecurityConfigurerAdapter

MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->MethodInvocation->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
/*~~(MethodInvocation type is missing or malformed)~~>*/http.csrf().disable()
              .antMatcher("/**")
	at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:87)
	at org.openrewrite.java.Assertions.validateTypes(Assertions.java:57)
	at org.openrewrite.java.Assertions$$Lambda$436/0x0000009801168b30.accept(Unknown Source)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:305)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:133)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
	at org.openrewrite.spring.security6.ApplyToWithLambdaDslTest.testDisableWithSessionManagementAndHttpBasic(ApplyToWithLambdaDslTest.java:318)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:765)
	
```

## Are you interested in [contributing a fix to OpenRewrite]
Im guessting the problem is caused in this particular [class](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDsl.java) which handles `HttpSecurityLambdaDsl`.

**Comment by timtebeek** [comment]
hi! Neat the see the additions you're working on in https://github.com/openrewrite/rewrite-spring/compare/main...freenowtech:rewrite-spring:http-security-lambda-dsl-tests ; appreciate you folks looking to contribute back to the project! 🙏🏻 

What's odd here is that you're reporting type issues with a test not modified in your branch 🤔 
`org.openrewrite.spring.security6.ApplyToWithLambdaDslTest.testDisableWithSessionManagementAndHttpBasic`.
Sometimes it helps to run `./gradlew downloadRecipeDependencies` locally; could that help you here as well?

**Comment by timtebeek** [comment]
Sure! The text blocks are missing an import, which leads to a missing type, which then throws the above error. We built this check into the testing framework as it leads to a lot of debugging when writing new tests, which should now be easier to troubleshoot.

```java
import org.springframework.security.config.http.SessionCreationPolicy;
```

**Comment by timtebeek** [comment]
Can we close this issue @ohyesgocool ? I think we've solved the test issue you had by adding that missing dependency right?

**Comment by ohyesgocool** [comment]
Hi @timtebeek , thanks for looking into the issue , yes we could close it. i will do it now
